// Generated by CoffeeScript 1.4.0
(function() {

  this.App || (this.App = {});

  App.FlashbackController = function($scope, $http) {
    return $scope.search = function() {
      var query, url;
      $scope.tweets = [];
      $scope.loading = true;
      query = $scope.query;
      url = "https://search.twitter.com/search.json?" + ("q=" + (encodeURIComponent(query)) + "&rpp=500&result_type=mixed&") + "callback=JSON_CALLBACK";
      return $http.jsonp(url).success(function(response) {
        $scope.tweets = response.results;
        return $scope.loading = false;
      });
    };
  };

}).call(this);
